app.factory("Translate", [
  "$state",
  function () {
    return {
      name: "Translate",
      rtl: {
        TEXT_DASHBOARD: "الصفحة الرئيسية",
        TEXT_USERS: "المستخدمين",
        TEXT_Roles: "الصلاحيات",
        TEXT_LOGOUT: "تسجل خروج",
        TEXT_CREATE_USER: "إنشاء مستخدم",
        TEXT_USER_CODE: "كود المستخدم",
        TEXT_USER_NAME: "أسم المستخدم",
        TEXT_USER_CREATION_DATE: "تاريخ الأنشاء",
        TEXT_FULL_NAME: "الأسم الكامل",
        TEXT_PASSWORD: "كلمة المرور",
        TEXT_USERNAME: "أسم المستخدم",
        TEXT_CONFIRM_PASSWORD: "تاكيد كلمة المرور",
        TEXT_AGENT: "مندوب",
        TEXT_EMPLOYEE: "موظف",
        TEXT_ADDRESS: "العنوان",
        TEXT_NATIONALITY: "الجنسية",
        TEXT_ADD_USER: "أضافة مستخدم",

        TEXT_PLACEHOLDER_SEARCH: "بحث ...",

        TEXT_EDIT: "تعديل",
        TEXT_EDIT_PERMISSIONS: "تعديل الصلاحيات",
        TEXT_REMOVE: "حذف",
        TEXT_ADD: "أضافة",
        TEXT_CANCEL: "إلغاء",
        TEXT_SAVE: "حفظ",
        TEXT_NEXT: "التالي",
        TEXT_OPTIONS: "الخيارات",

        TEXT_READ: "عرض",
        TEXT_CREATE: "إنشاء",
        TEXT_UPDATE: "تعديل",
        TEXT_DELETE: "حذف",
        TEXT_PERMISSION: "الصلاحية",

        TEXT_USERS_AND_PERMISSIONS: "المستخدمين و الآذونات",
        TEXT_GENERAL_LEDGER: "دفتر الاستاذ العام",
        TEXT_SALE_AND_PURCHASE: "البيع و الشراء",
        TEXT_INVENTORY: "المخزون",
        TEXT_HR: "الموارد البشرية",

        /* permissions */
        TEXT_CHART_OF_ACCOUNT: "دليل الحسابات",
        TEXT_COST_CENTERS: "مراكز التكلفة",
        TEXT_ASSETS: "الأصول",
        TEXT_SUPLIERS: "الموردين",
        TEXT_CUSTOMERS: "الزبائن",
        TEXT_BANKS: "البنوك",
        TEXT_CASES: "خزن",
        TEXT_TRANSACTIONS: "معاملات",

        TEXT_INVOICES: "الفواتير",
        TEXT_RETURNS: "المرتجعات",
        TEXT_FREE_RETURNS: "المرتجع الحر",
        TEXT_BRANSHES: "الافرع",
        TEXT_COMISSIONS: "العلاوات",
        TEXT_DISCOUNTS: "الخصومات",

        TEXT_WAREHOUSE: "المستودعات",
        TEXT_ITEMS: "المنتجات",
        TEXT_BARCODES: "الباركود",
        TEXT_UNITES: "الوحدات",

        TEXT_EMPLOYEE_FILES: "ملفات الموظفين",
        TEXT_PAYROLL: "كشف رواتب",
        TEXT_PAYSLIP: "قسائم دفع",
        TEXT_BENEFITS: "الاستحقاقات",
        TEXT_DEDUCTIONS: "الاستقطاعات",
        TEXT_HOLIDAYS: "الاجازات",

        TEXT_ITEMS: "المنتجات",
        TEXT_ITEM_CODE: "كود المنتج",
        TEXT_ITEM_NAME: "اسم المنتج",
        TEXT_ITEM_CREATION_DATE: "تاريخ انشاء المنتج",
        TEXT_CREATE_ITEM: "انشاء منتج",

        TEXT_CREATE_ITEM: "انشاء منتج",
        TEXT_ITEM_NAME: "اسم المنتج",
        TEXT_ITEM_DESCRIPTION: "وصف المنتج",
        TEXT_CHOOSE_CATEGORIES: "أختار الفئة الخاصة بالمنتج",

        // Messages
        MSG_NO_RESULT: "لا يوجد اى نتائح حالياً",
        MSG_REQUIRED: "مطلوب * من فضلك قم بملاء هذه الخانة اولاً",
        MSG_UNMATCHED: "كلمة المرور غير متطابقة",
        MSG_WENT_WRONG: "!حدث خطاء غير معلوم",
        MSG_Login_Failed: "أسم المستخدم او كلمة المرور غير صحيح :/",
        MSG_DUPLICATE_NAME: "هذا الاسم مستخدم بالفعل",

        // settings

        TEXT_SETTINGS: "الاعدادات",
        ADD: "اضافه",
        CANCEL: "الغاء",
        CHOOSE: "اختر",
        UPDATE: "تعديل",
        CONFIRM: "تاكيد",
        CONFIRMMESSAGE: "هل انت متاكد",
        //user

        TEXT_CREATE_USER: "اضافه مستخدم",
        TEXT_EDITUSER: "تعديل مستخدم",
        TEXT_USERS: "المستخدمين",
        USERNAME: "اسم المستخدم",
        ROLE: "الصلاحيه",
        ISACTIVE: "الحاله",
        Password: "الرقم السري",

        //Text_addcompany

        Text_addcompany: "اضافه شركه",
        Text_companyName: "اسم الشركه",
        Text_companyactivity: "نشاط الشركه",
        Text_companyRegNo: "رقم التسجيل",
        Text_companyTaxcard: "البطاقه الضريبيه",
        Text_companyAddress: "العنوان",
        Text_phone: "التليفون",
        Text_mobilephone: "التليفون المحمول",
        Text_Email: "الايميل",
        Text_website: "الموقع",
        Text_logo: "الشعار",
        Text_curreny: "العمله",
        Text_country: "الدوله",
        Text_branchName: "اسم الفرع",
        Text_addbranch: "اضافه فرع",
        TEXT_EDITCOMPANYINFO: "تعديل بيانات الشركه",
        TEXT_BRANCHLIST: "قائمه الفروع",
        TEXT_COMPANYSETTING: "اعدادات الشركه",
        TEXT_BRANCHSETTING: "اعدادات الفروع",
        Text_COMPANYINFO: "بيانات الشركه",
        TEXT_EDITBRANCHINFO: "تعدبل بيانات الفرع",

        //PRODUCT
        TEXT_ADDPRODUCT: "اضافه صنف",
        maininformation: "المعلومات الرئيسيه",
        TEXT_PRODUCTCODE: "كود الصنف",
        TEXT_PRODUCTNAME: "اسم الصنف",
        category: "المجموعه",
        store: "المخزن",
        TEXT_CATEGORY: "المجموعه",
        addProduct: "اضافة منتج ",
        store: "المخزن",
        demandLimit: "حد الطلب",
        addStore: "اضافة مخزن",
        addCategory: "اضافة وحدة",
        storeRequired: "المخزن مطلوب",
        description: "الوصف",
        descriptionRequired: "الوصف مطلوب",
        categoryName: "اسم المجموعة",
        code: "الكود",
        codeRequired: "الكود مطلوب",
        productName: "اسم المنتج",
        nameRequired: "الاسم مطلوب",
        productBarCode: "الباركود",
        units: "الوحدات",
        barCodeRequired: "الباركود مطلوب",
        price: "السعر",
        priceRequired: "السعر مطلوب",
        categoryadd: "اضافة مجموعه",
        categoryRequired: "المجموعة مطلوبة",
        sellerPrice: "سعر البيع",
        sellerPriceRequired: "سعر البيع مطلوب",
        purchesePrice: "سعر الشراء",
        purchesePriceRequired: "سعر الشراء مطلوب",
        tax: "الضريبة",
        taxRequired: "الضريبة مطلوبة",
        stock: "المخزون",
        stockRequired: "المخزون مطلوب",
        orderLimit: "حد الطلب",
        orderLimitRequired: "حد الطلب مطلوب",
        unitName: "اسم الوحدة",
        unitNameRequired: "اسم الوحدة مطلوب",
        sellingprice: "سعر البيع ",
        purchasingPric: "سعر الشراء",
        defaultSelling: "افتراضي بيع",
        defaultPurchasing: "افتراضي شراء",
        unitPriceRequired: "سعر الوحدة مطلوب",
        isExpiration: "له صلاحية",
        Expiration: "الصلاحيه",
        productionDate: "تاريخ الانتاج",
        productionDateRequired: "تاريخ الانتاج مطلوب ",
        expirationDate: "تاريخ الانتهاء",
        expirationDateRequired: "تاريخ الانتهاء مطلوب ",
        width: "العرض",
        widthRequired: "العرض مطلوب",
        height: "الطول",
        heightRequired: "الطول مطلوب",
        elevation: "الارتفاع",
        elevationRequired: "الارتفاع مطلوب",
        size: "الحجم",
        sizeRequired: "الحجم مطلوب",
        weight: "الوزن القائم",
        weightRequired: "مطلوب",
        netWeight: "الوزن الصافي",
        netWeightRequired: "مطلوب",
        selectStore: "اختر المخزن ",
        selectCategory: "اخترالتصنيف",
        units: "الوحدات",
        dimensions: "الابعاد",
        add: "اضافة",
        AddNewUnit: "اضافة وحده جديده",
        currentBalance: "الرصيد الحالي",
        startbakance: "الرصيد الافتتاحي",
        balanceUnit: "وحدة الرصيد الافتتاحي",
        balanceCost: "تكلفة الرصيد",
        completAccount: "الحساب المكمل",
        choseUnit: "---اختار وحدة---",
        choseAccount: "----اختار الحساب----",
        defaultSell: "افتراضي بيع",
        defaultPerchase: "افتراضي شراء",
        storeaccount: "المخزون",
        storeaccount: "رصيد المخزون",
        editproduct: "تعديل صنف",
        // dashboard
        DASHBOARD: "لوحه التحكم",
        //role
        Text_Roles: "الصلاحيات",
        Text_AddRole: "اضافة صلاحيه",
        Text_RoleName: "اسم الصلاحيه",
        Text_RoleRequired: "اسم الصلاحيه مطلوب",
        Text_deleteRole: "حذف الصلاحيه",
        Text_ManagePermission: "تعديل الصلاحيات",
        Text_AddAndDeletePermission: "اضافة /حذف صلاحيه",
        Text_Module: "اسم المسار",
        Text_PermissionModule: "الصلاحيه",
        Text_ConfirmdeleteRole: "هل انت متأكد من حذف الصلاحيه",
        //customers
        TEXT_ADDCUSTOMER: "اضافة عميل",
        TEXT_CUSTOMERS: "العملاء",
        TEXT_EXIST: "يوجد لديك عدد",
        TEXT_Customer: "عميل",
        TEXT_CustomerName: "اسم العميل",
        Text_Balance: "الرصيد",
        Text_Address: "العنوان",
        TEXT_customerRequired: "اسم العميل مطلوب",
        TEXT_AddressRequired: "العنوان مطلوب",
        TEXT_PhoneRequired: "رقم الموبايل مطلوب",
        TEXT_FAX: "الفاكس",
        TEXT_DISCOUNT: "الخصم",
        TEXT_DEBIT: "مدين",
        TEXT_CREDIT: "دائن",
        TEXT_HomeMobile: "التليفون الارضى",
        TEXT_UPDATECUSTOMER: "تعديل عميل",
        TEXT_CUSTOMERANDSUPPLIER: "عميل و مورد",
        //suppliers
        TEXT_ADDSUPPLIER: "اضافة مورد",
        TEXT_SUPPLIERS: "الموردين",
        TEXT_EXIST: "يوجد لديك عدد",
        TEXT_Supplier: "مورد",
        TEXT_SupplierName: "اسم المورد",
        Text_Balance: "الرصيد",
        Text_Address: "العنوان",
        TEXT_supplierRequired: "اسم المورد مطلوب",
        TEXT_AddressRequired: "العنوان مطلوب",
        TEXT_PhoneRequired: "رقم الموبايل مطلوب",
        TEXT_FAX: "الفاكس",
        TEXT_DISCOUNT: "الخصم",
        TEXT_DEBIT: "مدين",
        TEXT_CREDIT: "دائن",
        TEXT_HomeMobile: "التليفون الارضى",
        TEXT_UPDATESUPPLIER: "تعديل مورد",
        TEXT_SUPPLIERANDCUSTOMER: "مورد و عميل",
      },
      ltr: {
        TEXT_DASHBOARD: "Dashboard",
        TEXT_USERS: "Users",
        TEXT_LOGOUT: "Log out",
        TEXT_CREATE_USER: "Create user",
        TEXT_USER_CODE: "User code",
        TEXT_USER_NAME: "User name",
        TEXT_USER_CREATION_DATE: "User creation date",
        TEXT_FULL_NAME: "Full name",
        TEXT_PASSWORD: "Password",
        TEXT_USERNAME: "User name",
        TEXT_CONFIRM_PASSWORD: "Confirm password",
        TEXT_AGENT: "Agent",
        TEXT_EMPLOYEE: "Employee",
        TEXT_ADDRESS: "Address",
        TEXT_NATIONALITY: "Nationality",
        TEXT_ADD_USER: "Add user",

        TEXT_PLACEHOLDER_SEARCH: "Search ...",

        TEXT_EDIT: "Edit",
        TEXT_EDIT_PERMISSIONS: "Edit permissions",
        TEXT_REMOVE: "Remove",
        TEXT_ADD: "Add",
        TEXT_CANCEL: "Cancel",
        TEXT_CREATE: "Create",
        TEXT_SAVE: "Save",
        TEXT_NEXT: "Next",
        TEXT_OPTIONS: "Options",

        TEXT_READ: "Read",
        TEXT_CREATE: "Create",
        TEXT_UPDATE: "Edit",
        TEXT_DELETE: "Delete",
        TEXT_PERMISSION: "Permission",

        TEXT_USERS_AND_PERMISSIONS: "Users and permissions",
        TEXT_GENERAL_LEDGER: "General ledger",
        TEXT_SALE_AND_PURCHASE: "Sale and purchase",
        TEXT_INVENTORY: "Inventory",
        TEXT_HR: "Human resources",

        /* permissions */
        TEXT_CHART_OF_ACCOUNT: "Chart of account",
        TEXT_COST_CENTERS: "Cost centers",
        TEXT_ASSETS: "Assets",
        TEXT_SUPLIERS: "Suppliers",
        TEXT_CUSTOMERS: "Customers",
        TEXT_BANKS: "Banks",
        TEXT_CASES: "Cases",
        TEXT_TRANSACTIONS: "Transactions",

        TEXT_INVOICES: "Invoices",
        TEXT_RETURNS: "Returns",
        TEXT_FREE_RETURNS: "Free return",
        TEXT_BRANSHES: "Branshes",
        TEXT_COMISSIONS: "Comissions",
        TEXT_DISCOUNTS: "Discounts",

        TEXT_WAREHOUSE: "Warehouse",
        TEXT_ITEMS: "Items",
        TEXT_BARCODES: "Barcodes",
        TEXT_UNITES: "Unites",

        TEXT_EMPLOYEE_FILES: "Employee files",
        TEXT_PAYROLL: "payroll",
        TEXT_PAYSLIP: "payslip",
        TEXT_BENEFITS: "benefits",
        TEXT_DEDUCTIONS: "deductions",
        TEXT_HOLIDAYS: "Holidays",

        TEXT_ITEMS: "Items",
        TEXT_ITEM_CODE: "Item code",
        TEXT_ITEM_NAME: "Item name",
        TEXT_ITEM_CREATION_DATE: "Item creation date",
        TEXT_CREATE_ITEM: "Create item",

        TEXT_CREATE_ITEM: "Create item",
        TEXT_ITEM_NAME: "Item name",
        TEXT_ITEM_DESCRIPTION: "Item Description",
        TEXT_CHOOSE_CATEGORIES: "Choose categories of item",

        // Messages
        MSG_NO_RESULT: "There's No Results Now",
        MSG_REQUIRED: "Required *  please fill this field first",
        MSG_UNMATCHED: "Password is not matched",
        MSG_WENT_WRONG: "Something went wrong !",
        MSG_Login_Failed: "Username or password wrong :/",
        MSG_DUPLICATE_NAME: "This username is already taken",

        // settings
        TEXT_SETTINGS: "Settings",
        ADD: "Add",
        CANCEL: "Cancel",
        CHOOSE: "Choose",
        UPDATE: "Update",
        CONFIRM: "Confirm",
        CONFIRMMESSAGE: "Are You Sure",

        //adduser

        TEXT_CREATE_USER: "Add User",
        TEXT_EDITUSER: "Edit User",
        TEXT_USERS: "Users",
        USERNAME: "User Name",
        ROLE: "Role",
        ISACTIVE: "IsActive",
        Password: "Password",

        //Text_addcompany

        Text_addcompany: "Add Company",
        Text_companyName: "Company Name",
        Text_companyactivity: "Company Activity",
        Text_companyRegNo: "REgistration No",
        Text_companyTaxcard: "Tax Card",
        Text_companyAddress: "Address",
        Text_phone: "Phone",
        Text_mobilephone: "Mobile Phone",
        Text_Email: "Email",
        Text_website: "Website",
        Text_logo: "Logo",
        Text_curreny: "Currency",
        Text_country: "Country",
        Text_branchName: "Branch Name",
        Text_addbranch: "Add Branch",
        TEXT_EDITCOMPANYINFO: "Edit Company Information",
        TEXT_BRANCHLIST: "Branch List",
        TEXT_COMPANYSETTING: "Company Setting",
        TEXT_BRANCHSETTING: "Branches Setting",
        Text_COMPANYINFO: "Company Information",

        //role
        Text_Roles: "Roles",
        Text_AddRole: "AddRole",
        Text_RoleName: "Role Name",
        Text_RoleRequired: "role name is required",
        Text_deleteRole: "delete role",
        Text_ManagePermission: "manage permissions",
        Text_AddAndDeletePermission: " Add/Remove Permissions",
        Text_Module: "Module",
        Text_ConfirmdeleteRole: "Are you sure delete role ?",
        //customers
        TEXT_CUSTOMERS: "Customers",
        TEXT_EXIST: "You have total",
        TEXT_Customer: "customers",
        TEXT_CustomerName: "Customer Name",
        Text_Balance: "Balance",
        Text_Address: "Address",
        TEXT_customerRequired: "customer Name required",
        TEXT_AddressRequired: "address is required.",
        TEXT_PhoneRequired: "phone is required",
        TEXT_FAX: "Fax",
        TEXT_DISCOUNT: "Discount",
        TEXT_HomeMobile: "Home Mobile",
        TEXT_DEBIT: "Debit",
        TEXT_CREDIT: "Credit",
        TEXT_CUSTOMERANDSUPPLIER: "customerAndSupplier",
        TEXT_ADDCUSTOMER: "Add Customer",
        TEXT_UPDATECUSTOMER: "update customer",

        //suppliers
        TEXT_SUPPLIERS: "Suppliers",
        TEXT_EXIST: "You have total",
        TEXT_Supplier: "suppliers",
        TEXT_SupplierName: "Supplier Name",
        Text_Balance: "Balance",
        Text_Address: "Address",
        TEXT_supplierRequired: "supplier Name required",
        TEXT_AddressRequired: "address is required.",
        TEXT_PhoneRequired: "phone is required",
        TEXT_FAX: "Fax",
        TEXT_DISCOUNT: "Discount",
        TEXT_HomeMobile: "Home Mobile",
        TEXT_DEBIT: "Debit",
        TEXT_CREDIT: "Credit",
        TEXT_SUPPLIERANDCUSTOMER: "supplierAndCupplier",
        TEXT_ADDSUPPLIER: "Add Supplier",
        TEXT_UPDATESUPPLIER: "update supplier",

        //dashboard
        DASHBOARD: "Dashboard",
        //role
        Text_Roles: "Roles",
        Text_AddRole: "AddRole",
        Text_RoleName: "Role Name",
        Text_RoleRequired: "role name is required",
        Text_deleteRole: "delete role",
        Text_ManagePermission: "manage permissions",
        Text_AddAndDeletePermission: " Add/Remove Permissions",
        Text_Module: "Module",
        Text_ConfirmdeleteRole: "Are you sure delete role ?",
      },
    };
  },
]);
